---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-automation-controller.yaml
  - image-reflector-controller.yaml
images:
  - name: fluxcd/image-automation-controller
    newName: registry1.dso.mil/ironbank/fluxcd/image-automation-controller
  - name: fluxcd/image-reflector-controller
    newName: registry1.dso.mil/ironbank/fluxcd/image-reflector-controller
labels:
  - pairs:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
patches:
  # CIS hardening
  - target:
      kind: ServiceAccount
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: all
      automountServiceAccountToken: false
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: whatever
      spec:
        template:
          metadata:
            annotations:
              # Required by Kubernetes node autoscaler
              cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          spec:
            terminationGracePeriodSeconds: 60
            automountServiceAccountToken: true
            # Required by Pod Security Policy
            securityContext:
              runAsUser: 65432
              fsGroup: 65432
            containers:
              - name: manager
                # Required by Pod Security Policy
                securityContext:
                  runAsUser: 65432
                  runAsGroup: 65432
                  privileged: false
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  capabilities:
                    drop:
                      - ALL
                  $patch: replace
